#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall polybar
polybar example &
wmname LG3D

bspc monitor HDMI-0 -d I II III
bspc monitor DP-1   -d A
bspc monitor DP-5   -d B

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true